### ISSUE TITLE
User story 4 - IATA code and timezone

### ISSUE THREAD

**Issue by MBVeilis** [KongBoje/momondoproject#12]
As a user, I want to be able to search for the destinations IATA code and timezone, so that I can get fast information about the destination

**Comment by MBVeilis** [comment]
Tasks:

**Comment by TreasureSchool** [comment]
Implement a JSON call to an external API with timezones and IATA codes.

Alternatively if needed to be done locally:

Implement destinations' timezones and IATA Codes in entities and tables
Implement methods to fetch these
Implement methods to reach the fetching methods through JSON
Implement a search call that pulls info from the JSON methods.
Make exception and error handling
