### ISSUE TITLE
User story 2 - Available flights from specific airport with the given time and date.

### ISSUE THREAD

**Issue by MBVeilis** [KongBoje/momondoproject#2]
As a user, I want to be able to get all available flights from the specific airport with the given date and time, so that I know what options I have.

**Comment by MBVeilis** [comment]
Tasks:

**Comment by TreasureSchool** [comment]
Generate the HTML/angular flight table. => Pair programming
Make proxy API to fetch from external flight API. => Pair programming
Develop the methods that turn the entities into JSON objects. => Pair programming
Develop the methods that put the JSON objects onto our webpage. => Pair programming
Make Exception/error handling for the system. => Pair programming
