### ISSUE TITLE
User story 5 - From given airport to another

### ISSUE THREAD

**Issue by MBVeilis** [KongBoje/momondoproject#5]
As a user, I want to see all flights going from one airport to another with a given date, so that I know when I can travel.

**Comment by MBVeilis** [comment]
Tasks:

**Comment by TreasureSchool** [comment]
Generate the HTML/angular flight table. => Pair programming
Make proxy API to fetch from external flight API. => Pair programming
Develop the methods that turn the entities into JSON objects. => Pair programming
Develop the methods that put the JSON objects onto our webpage. => Pair programming
