### ISSUE TITLE
User story 6 - Login (mangler tidyness)

### ISSUE THREAD

**Issue by MBVeilis** [KongBoje/momondoproject#7]
As a user, I want to be able to log in, so that I can access my information.

This counts for both the user and the admin

**Comment by MBVeilis** [comment]
Tasks:

**Comment by TreasureSchool** [comment]
Develop the User entities and related tables
Implement methods that let you access/edit the related tables
Develop methods that let you access the former methods through the webpages
Implement a login form that uses these methods.
Optionally, implement verification.
Make exception and error handling
